---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: deploy
  namespace: kapp-controller
spec:
  fetch:
  - git:
      url: https://github.com/voor/cluster-api-gitops
      ref: origin/master
      subPath: workload/deploy
      secretRef:
        name: #@ data.values.git.secretRef
  template:
  - ytt:
      ignoreUnknownComments: true
  deploy:
  - kapp:
      deploy:
        rawOptions: 
        - "--wait=false"